services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: vitta-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL} 
      - PORT=3000
    networks:
      - traefik_proxy_network
      - shared_backend_network

  # --- VITTA FRONTEND SERVICE ---
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL} 
    container_name: vitta-frontend
    restart: unless-stopped
    networks:
      - traefik_proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy_network"

      - "traefik.http.routers.vitta-http.rule=Host(`vitta.gsaraiva.com.br`)"
      - "traefik.http.routers.vitta-http.entrypoints=web"
      - "traefik.http.routers.vitta-http.middlewares=httpsredirect@file"

      - "traefik.http.routers.vitta-frontend-secure.rule=Host(`vitta.gsaraiva.com.br`)"
      - "traefik.http.routers.vitta-frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.vitta-frontend-secure.service=vitta-frontend-svc"
      - "traefik.http.routers.vitta-frontend-secure.priority=1"
      - "traefik.http.routers.vitta-frontend-secure.tls=true"
      - "traefik.http.routers.vitta-frontend-secure.tls.certresolver=lets-encrypt"

      - "traefik.http.routers.vitta-backend-secure.rule=Host(`vitta.gsaraiva.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.vitta-backend-secure.entrypoints=websecure"
      - "traefik.http.routers.vitta-backend-secure.service=vitta-backend-svc"
      - "traefik.http.routers.vitta-backend-secure.priority=10"
      - "traefik.http.routers.vitta-backend-secure.tls=true"
      - "traefik.http.routers.vitta-backend-secure.tls.certresolver=lets-encrypt"
      
      - "traefik.http.routers.vitta-backend-secure.middlewares=strip-api-prefix"
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.services.vitta-frontend-svc.loadbalancer.server.port=80"
      - "traefik.http.services.vitta-backend-svc.loadbalancer.server.port=3000"

networks:
  shared_backend_network:
    external: true
  traefik_proxy_network:
    external: true