services:
  vitta-frontend:
    image: 'nginx:alpine'
    container_name: vitta-frontend
    restart: unless-stopped
    volumes:
      - './dist:/usr/share/nginx/html'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:80/health'
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - traefik_proxy_network
      - shared_backend_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy_network"
      
      - "traefik.http.routers.vitta-http.rule=Host(`vitta.gsaraiva.com.br`)"
      - "traefik.http.routers.vitta-http.entrypoints=web"
      - "traefik.http.routers.vitta-http.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.vitta-frontend-secure.rule=Host(`vitta.gsaraiva.com.br`)"
      - "traefik.http.routers.vitta-frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.vitta-frontend-secure.service=vitta-frontend-svc"
      - "traefik.http.routers.vitta-frontend-secure.priority=1"
      - "traefik.http.routers.vitta-frontend-secure.tls=true"
      - "traefik.http.routers.vitta-frontend-secure.tls.certresolver=lets-encrypt"
      - 'traefik.http.routers.vitta-backend-secure.rule=Host(`vitta.gsaraiva.com.br`) && PathPrefix(`/api`)'
      - "traefik.http.routers.vitta-backend-secure.entrypoints=websecure"
      - "traefik.http.routers.vitta-backend-secure.service=vitta-backend-svc"
      - "traefik.http.routers.vitta-backend-secure.priority=10"
      - "traefik.http.routers.vitta-backend-secure.tls=true"
      - "traefik.http.routers.vitta-backend-secure.tls.certresolver=lets-encrypt"
      
      - "traefik.http.routers.vitta-backend-secure.middlewares=strip-api-prefix"
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      
      - "traefik.http.services.vitta-frontend-svc.loadbalancer.server.port=443"
      - "traefik.http.services.vitta-backend-svc.loadbalancer.server.port=3000"

  vitta-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitta-backend
    restart: unless-stopped
    environment:
      - 'DATABASE_URL=${DATABASE_URL}'
      - PORT=3000
    networks:
      - traefik_proxy_network
      - shared_backend_network

networks:
  shared_backend_network:
    external: true
  traefik_proxy_network:
    external: true